version: '3'

services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "127.0.0.1:5432:5432"
      